# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2017-01-02 20:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserHome',
            fields=[
                ('uid', models.BigIntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=255)),
                ('home', models.CharField(max_length=255)),
                ('lang', models.IntegerField()),
            ],
        ),
    ]
